version: "3"
services:
  db:
    image: "postgres"
    container_name: "collectables_db"
    environment:
      - POSTGRES_USER=collectables
      - POSTGRES_PASSWORD=geheim1
      - POSTGRES_DB=collectables
    ports:
      - "5432:5432"
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data