spring:
    jpa:
        hibernate:
            ddl-auto: none
    database:
        driver-class-name: org.postgresql.Driver
    datasource:
        url: jdbc:postgresql://localhost:5432/collectables
        username: collectables
        password: geheim1

# actuator specific
management:
  context-path: /status

---

spring:
    profiles: heroku
    datasource:
        url: jdbc:postgresql://ec2-23-21-255-14.compute-1.amazonaws.com:5432/d3m08ag2bi8g8o
        username: ofshvoqtzunatz
        password: LSVJxChVBSjMPfyOtnIMVz3lRQ
